CREATE TABLE USERS (
ID NUMBER NOT NULL,
CONSTRAINT USERS_PK PRIMARY KEY (ID),
NAME NVARCHAR2(30) NOT NULL,
NICK_NAME NVARCHAR2(10) NOT NULL,
PASSWORD NVARCHAR2(15) NOT NULL,
AGE NUMBER,
COMPANY NVARCHAR2(15),
FRIENDS_COUNT NUMBER
)

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1001, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1002, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1003, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1004, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1005, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1006, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1007, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1008, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1009, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

INSERT INTO USERS (ID, NAME, NICK_NAME, PASSWORD, AGE, COMPANY, FRIENDS_COUNT)
VALUES (1010, 'John', 'Red', '12345qwert', '23', 'IBM', '0');

SELECT COUNT(*) FROM USERS;

SELECT COUNT(*) FROM USERS WHERE FRIENDS_COUNT > 10;

SELECT COUNT(*) FROM USERS WHERE AGE > 21 AND COMPANY = 'Google';

SELECT * FROM USERS WHERE NAME = 'Denis' OR NAME = 'Denis';

UPDATE USERS
SET COMPANY = 'Amazon';

SELECT COUNT(*) FROM USERS WHERE COMPANY = 'Amazon' OR COMPANY = 'Google';

DELETE FROM USERS
WHERE COMPANY IS NULL;

SELECT COUNT(*) FROM USERS;

ALTER TABLE USERS
ADD CITY NVARCHAR2(15);

SELECT * FROM USERS
WHERE COMPANY = 'Amazon' AND CITY = 'Dublin' OR CITY = 'Kiev ' OR CITY = 'Seattle';

ALTER TABLE USERS
RENAME COLUMN AGE TO WORK_EXPERIENCE;

UPDATE USERS
SET WORK_EXPERIENCE = '5'
WHERE  NAME = 'Artem';